<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Array element type not supported (on key "{key}").' => 'El elemento de tipo arreglo no se admite (en clave "{key}").',
  'Array key type not supported.' => 'Clave de tipo arreglo no compatible.',
  'Cannot save the related records to the database because the main record is new.' => 'No se puede guardar los registros relacionados con la base de datos debido a que el registro principal es nuevo.',
  'Composite primary keys are not supported.' => 'Claves primarias compuestas no son compatibles.',
  'Object serialization is not supported (on key "{key}").' => 'La serialización de objetos no es compatible (en clave "{key}").',
  'Related model not found. Cannot continue without filling up the FK.' => 'Modelo relacional no encontrado. No se puede continuar sin llenar el FK.',
  'The argument "data" must be of type string or array.' => 'El argumento "data" debe ser de tipo cadena o una matriz.',
  'The attribute "{attribute}" should be the last name.' => 'El atributo "{attribute}" debe ser el último nombre.',
  'The count of values in the argument "pk" ({countPk}) does not match the count of columns in the composite PK ({countColumns}).' => 'El recuento de los valores en el argumento "pk" ({countPk}) no coincide con el número de columnas en el PK compuesto ({countColumns}).',
  'The representing column for the active record "{model}" is not set.' => 'La columna que representa para el registro activo "{model}" no se ha establecido.',
  'The requested page does not exist.' => 'La página solicitada no existe.',
  'This method should be overriden by the Active Record class.' => 'Este método debe ser sobreescrito por la clase Active Record.',
  'Your request is invalid.' => 'Su solicitud no es válida.',
  'giix cannot handle automatically the POST data if "uncheckValue" is null.' => 'giix no puede manejar de forma automática los datos POST si "uncheckValue" es nulo.',
);
