<?php

/**
 * This is the model base class for the table "asignatura".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Asignatura".
 *
 * Columns in table "asignatura" available as properties of the model,
 * followed by relations of table "asignatura" available as properties of the model.
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $semestre
 * @property string $programa
 * @property string $codigo
 * @property integer $numero
 * @property integer $catedra
 * @property integer $taller
 * @property integer $laboratorio
 * @property string $tipo_formacion
 *
 * @property AsignaturaPrerequisito[] $asignaturaPrerequisitos
 * @property AsignaturaPrerequisito[] $asignaturaPrerequisitos1
 * @property Curso[] $cursos
 */
  
abstract class BaseAsignatura extends GxActiveRecord {

       
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'asignatura';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Asignatura|Asignaturas', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('semestre, numero, catedra, taller, laboratorio', 'numerical', 'integerOnly'=>true),
			array('nombre', 'length', 'max'=>255),
			array('codigo', 'length', 'max'=>45),
			array('tipo_formacion', 'length', 'max'=>100),
			array('programa', 'safe'),
			array('nombre, semestre, programa, codigo, numero, catedra, taller, laboratorio, tipo_formacion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, nombre, semestre, programa, codigo, numero, catedra, taller, laboratorio, tipo_formacion', 'safe', 'on'=>'search'),
		);                        
	}

	public function relations() {
		return array(
			'asignaturaPrerequisitos' => array(self::HAS_MANY, 'AsignaturaPrerequisito', 'asignatura_id'),
			'asignaturaPrerequisitos1' => array(self::HAS_MANY, 'AsignaturaPrerequisito', 'prerequisito_asignatura_id'),
			'cursos' => array(self::HAS_MANY, 'Curso', 'asignatura_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'nombre' => Yii::t('app', 'Nombre'),
			'semestre' => Yii::t('app', 'Semestre'),
			'programa' => Yii::t('app', 'Programa'),
			'codigo' => Yii::t('app', 'Codigo'),
			'numero' => Yii::t('app', 'Numero'),
			'catedra' => Yii::t('app', 'Catedra'),
			'taller' => Yii::t('app', 'Taller'),
			'laboratorio' => Yii::t('app', 'Laboratorio'),
			'tipo_formacion' => Yii::t('app', 'Tipo Formacion'),
			'asignaturaPrerequisitos' => null,
			'asignaturaPrerequisitos1' => null,
			'cursos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('semestre', $this->semestre);
		$criteria->compare('programa', $this->programa, true);
		$criteria->compare('codigo', $this->codigo, true);
		$criteria->compare('numero', $this->numero);
		$criteria->compare('catedra', $this->catedra);
		$criteria->compare('taller', $this->taller);
		$criteria->compare('laboratorio', $this->laboratorio);
		$criteria->compare('tipo_formacion', $this->tipo_formacion, true);
                
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
                        'pagination'=>array('pageSize'=>500),
		));
	}
        
  
        
}