<?php

/**
 * This is the model base class for the table "plan_actividad".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PlanActividad".
 *
 * Columns in table "plan_actividad" available as properties of the model,
 * followed by relations of table "plan_actividad" available as properties of the model.
 *
 * @property integer $id
 * @property integer $curso_id
 * @property integer $planificacion_semestral_id
 * @property string $fecha_inicio
 * @property string $fecha_termino
 * @property string $actividad
 *
 * @property Curso $curso
 * @property PlanificacionSemestral $planificacionSemestral
 */
  
abstract class BasePlanActividad extends GxActiveRecord {

        public $fecha_inicio_inicio;
        public $fecha_inicio_termino;
        public $fecha_termino_inicio;
        public $fecha_termino_termino;
       
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'plan_actividad';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Plan Actividad|Plan Actividads', $n);
	}

	public static function representingColumn() {
		return 'fecha_inicio';
	}

	public function rules() {
		return array(
			array('curso_id, planificacion_semestral_id', 'required'),
			array('curso_id, planificacion_semestral_id', 'numerical', 'integerOnly'=>true),
			array('actividad', 'length', 'max'=>255),
			array('fecha_inicio, fecha_termino', 'safe'),
			array('fecha_inicio, fecha_termino, actividad', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, curso_id, planificacion_semestral_id, fecha_inicio, fecha_termino, actividad, fecha_inicio_inicio, fecha_inicio_termino, fecha_termino_inicio, fecha_termino_termino', 'safe', 'on'=>'search'),
		);                        
	}

	public function relations() {
		return array(
			'curso' => array(self::BELONGS_TO, 'Curso', 'curso_id'),
			'planificacionSemestral' => array(self::BELONGS_TO, 'PlanificacionSemestral', 'planificacion_semestral_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'curso_id' => null,
			'planificacion_semestral_id' => null,
			'fecha_inicio' => Yii::t('app', 'Fecha Inicio'),
			'fecha_termino' => Yii::t('app', 'Fecha Termino'),
			'actividad' => Yii::t('app', 'Actividad'),
			'curso' => null,
			'planificacionSemestral' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('curso_id', $this->curso_id);
		$criteria->compare('planificacion_semestral_id', $this->planificacion_semestral_id);
                $criteria->compare('fecha_inicio', Yii::app()->format->FormatoFechaBD($this->fecha_inicio), true);
                if(!empty($this->fecha_inicio_inicio) && !empty($this->fecha_inicio_termino))   
                        $criteria->addBetweenCondition('fecha_inicio', Yii::app()->format->FormatoFechaBD($this->fecha_inicio_inicio), Yii::app()->format->FormatoFechaBD($this->fecha_inicio_termino));
                $criteria->compare('fecha_termino', Yii::app()->format->FormatoFechaBD($this->fecha_termino), true);
                if(!empty($this->fecha_termino_inicio) && !empty($this->fecha_termino_termino))   
                        $criteria->addBetweenCondition('fecha_termino', Yii::app()->format->FormatoFechaBD($this->fecha_termino_inicio), Yii::app()->format->FormatoFechaBD($this->fecha_termino_termino));
		$criteria->compare('actividad', $this->actividad, true);
                
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
        
        public function behaviors()
        {
            return array('datetimeI18NBehavior' => array('class' => 'ext.DateTimeI18NBehavior.DateTimeI18NBehavior'));
        }
  
        
}