<?php

/**
 * This is the model base class for the table "curso_tiene_alumno".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CursoTieneAlumno".
 *
 * Columns in table "curso_tiene_alumno" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $curso_id
 * @property integer $alumno_id
 * @property string $estado
 * @property double $promedio
 * @property integer $semestre
 * @property integer $anio
 *
 */
  
abstract class BaseCursoTieneAlumno extends GxActiveRecord {

       
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'curso_tiene_alumno';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Curso Tiene Alumno|Curso Tiene Alumnos', $n);
	}

	public static function representingColumn() {
		return array(
			'curso_id',
			'alumno_id',
		);
	}

	public function rules() {
		return array(
			array('curso_id, alumno_id', 'required'),
			array('curso_id, alumno_id', 'numerical', 'integerOnly'=>true),
			array('promedio', 'numerical','min'=>1,'max'=>7),
			array('estado', 'length', 'max'=>45),
			array('estado, promedio', 'default', 'setOnEmpty' => true, 'value' => null),
			array('curso_id, alumno_id, estado, promedio', 'safe', 'on'=>'search'),
		);                        
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'curso_id' => null,
			'alumno_id' => null,
			'estado' => Yii::t('app', 'Estado'),
			'promedio' => Yii::t('app', 'Promedio'),
			'semestre' => Yii::t('app', 'Semestre'),
			'anio' => Yii::t('app', 'Anio'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('curso_id', $this->curso_id);
		$criteria->compare('alumno_id', $this->alumno_id);
		$criteria->compare('estado', $this->estado, true);
		$criteria->compare('promedio', $this->promedio);
		$criteria->compare('semestre', $this->semestre);
		$criteria->compare('anio', $this->anio);
                
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
        
  
        
}