<?php

/**
 * This is the model base class for the table "curso".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Curso".
 *
 * Columns in table "curso" available as properties of the model,
 * followed by relations of table "curso" available as properties of the model.
 *
 * @property integer $id
 * @property integer $asignatura_id
 * @property integer $profesor_id
 * @property integer $semestre
 * @property integer $anio
 * @property string $nombre
 * @property string $estado
 *
 * @property Calificacion[] $calificacions
 * @property Asignatura $asignatura
 * @property Profesor $profesor
 * @property Alumno[] $alumnos
 * @property Evaluacion[] $evaluacions
 * @property PlanActividad[] $planActividads
 */
  
abstract class BaseCurso extends GxActiveRecord {

       
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'curso';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Curso|Cursos', $n);
	}

	public static function representingColumn() {
		return 'nombre';
	}

	public function rules() {
		return array(
			array('asignatura_id, profesor_id', 'required'),
			array('asignatura_id, profesor_id, semestre, anio', 'numerical', 'integerOnly'=>true),
			array('nombre, estado', 'length', 'max'=>255),
			array('semestre, anio, nombre, estado', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, asignatura_id, profesor_id, semestre, anio, nombre, estado', 'safe', 'on'=>'search'),
		);                        
	}

	public function relations() {
		return array(
			'calificacions' => array(self::HAS_MANY, 'Calificacion', 'curso_id'),
                        'curso_alumnos' => array(self::HAS_MANY, 'CursoTieneAlumno', 'curso_id'),
			'asignatura' => array(self::BELONGS_TO, 'Asignatura', 'asignatura_id'),
			'profesor' => array(self::BELONGS_TO, 'Profesor', 'profesor_id'),
			'alumnos' => array(self::MANY_MANY, 'Alumno', 'curso_tiene_alumno(curso_id, alumno_id)'),
			'evaluacions' => array(self::HAS_MANY, 'Evaluacion', 'curso_id'),
			'planActividads' => array(self::HAS_MANY, 'PlanActividad', 'curso_id'),
		);
	}

	public function pivotModels() {
		return array(
			'alumnos' => 'CursoTieneAlumno',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'asignatura_id' => null,
			'profesor_id' => null,
			'semestre' => Yii::t('app', 'Semestre'),
			'anio' => Yii::t('app', 'Anio'),
			'nombre' => Yii::t('app', 'Nombre'),
			'estado' => Yii::t('app', 'Estado'),
			'calificacions' => null,
			'asignatura' => null,
			'profesor' => null,
			'alumnos' => null,
			'evaluacions' => null,
			'planActividads' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('asignatura_id', $this->asignatura_id);
		$criteria->compare('profesor_id', $this->profesor_id);
		$criteria->compare('semestre', $this->semestre);
		$criteria->compare('anio', $this->anio);
		$criteria->compare('nombre', $this->nombre, true);
		$criteria->compare('estado', $this->estado, true);
                
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
        
  
        
}