<?php

/**
 * This is the model base class for the table "user".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "User".
 *
 * Columns in table "user" available as properties of the model,
 * followed by relations of table "user" available as properties of the model.
 *
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $email
 * @property string $rol
 * @property integer $activo
 *
 * @property Alumno[] $alumnos
 * @property PlanificacionSemestral[] $planificacionSemestrals
 * @property Profesor[] $profesors
 */
  
abstract class BaseUser extends GxActiveRecord {

       
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'user';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'User|Users', $n);
	}

	public static function representingColumn() {
		return 'username';
	}

	public function rules() {
		return array(
			array('username, password, activo', 'required'),
			array('activo', 'numerical', 'integerOnly'=>true),
			array('username, password, email', 'length', 'max'=>128),
			array('rol', 'length', 'max'=>45),
			array('email, rol', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, username, password, email, rol, activo', 'safe', 'on'=>'search'),
		);                        
	}

	public function relations() {
		return array(
			'alumnos' => array(self::HAS_MANY, 'Alumno', 'user_id'),
			'planificacionSemestrals' => array(self::HAS_MANY, 'PlanificacionSemestral', 'user_id'),
			'profesors' => array(self::HAS_MANY, 'Profesor', 'user_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'username' => Yii::t('app', 'Username'),
			'password' => Yii::t('app', 'Password'),
			'email' => Yii::t('app', 'Email'),
			'rol' => Yii::t('app', 'Rol'),
			'activo' => Yii::t('app', 'Activo'),
			'alumnos' => null,
			'planificacionSemestrals' => null,
			'profesors' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('rol', $this->rol, true);
		$criteria->compare('activo', $this->activo);
                
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
        
  
        
}